[package]
name = "gimli-permutation"
version = "0.1.1"
authors = ["quininer <quininer@live.com>"]
description = "Gimli: a cross-platform permutation"
repository = "https://github.com/quininer/gimli"
keywords = [ "permutation", "cryptography", "simd" ]
categories = [ "cryptography", "no-std" ]
license = "MIT"


[features]
simd = [ "coresimd" ]

[dependencies]
coresimd = { version = "0.0.4", optional = true }
