[package]
name = "gimli-hash"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]

[dependencies]
byteorder = { version = "1", default-features = false }
gimli-permutation = { path = "../gimli-permutation" }


[dev-dependencies]
hex = "0.3"
