name: CI

on:
  push:
    branches:
    - master
  pull_request: {}

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Check
        run: cargo check --all --all-features --all-targets

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ubuntu-latest
        rust: [stable]

    env:
      RUSTFLAGS: "-D warnings"

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
    - uses: actions/checkout@master
    - name: Test
      run: cargo test --all
    - name: Test Simd
      run: cargo test --all --all-features
